[package]
name = "madsim"
version = "0.1.1"
edition = "2018"
authors = ["Runji Wang <wangrunji0408@163.com>"]
description = "Deterministic Simulator for distributed systems."
readme = "../README.md"
homepage = "https://github.com/madsys-dev/madsim"
repository = "https://github.com/madsys-dev/madsim"
license = "Apache-2.0"
keywords = ["distributed-systems", "async", "deterministic", "simulation"]
categories = ["asynchronous", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["macros"]
sim = ["madsim-sim"]
std = ["madsim-std"]
macros = ["madsim-macros"]
rpc = ["serde", "bytes", "bincode"]

[dependencies]
madsim-macros = { path = "../madsim-macros", optional = true }
madsim-sim = { path = "../madsim-sim", optional = true }
madsim-std = { path = "../madsim-std", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
bytes = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }
thiserror = "1.0"

[dev-dependencies]
madsim-macros = { path = "../madsim-macros" }

[[bench]]
name = "rpc"
harness = false

[package.metadata.docs.rs]
all-features = true
